import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(root, "dist", "client");
const target = path.join(root, "public_html");

await mkdir(source, { recursive: true });
await rm(target, { recursive: true, force: true });
await cp(source, target, { recursive: true });

await writeFile(
  path.join(target, ".htaccess"),
  `DirectoryIndex index.html
Options -Indexes

RewriteEngine On
RewriteBase /

# Serve extensionless page URLs from the static HTML generated by vinext.
RewriteRule ^(activities|en|th|zh)/?$ $1.html [L]
RewriteRule ^404/?$ 404.html [L]
`,
);

console.log(`Prepared WP Plus files in ${path.relative(root, target)}/`);
